# Generated by Django 5.0.7 on 2024-07-18 05:44

import django.db.models.deletion
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_level', models.CharField(max_length=256, verbose_name='Рівень автомобіля')),
                ('day_1', models.IntegerField(max_length=25, verbose_name='1 день оренди')),
                ('day_3', models.IntegerField(max_length=25, verbose_name='3 дні оренди')),
                ('day_5', models.IntegerField(max_length=25, verbose_name='5 днів оренди')),
                ('day_7', models.IntegerField(max_length=25, verbose_name='7 днів оренди')),
                ('day_14', models.IntegerField(max_length=25, verbose_name='14 днів оренди')),
                ('day_30', models.IntegerField(max_length=25, verbose_name='30 днів оренди')),
            ],
            options={
                'verbose_name': 'Вартість оренди за автомобіль',
                'verbose_name_plural': 'Вартість оренди за автомобіль',
                'db_table': 'app_car_price',
            },
        ),
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.CharField(max_length=256, null=True, verbose_name='Марка')),
                ('car_model', models.CharField(max_length=256, null=True, verbose_name='Модель')),
                ('image', models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/Users/oleh/PycharmProjects/car_rental/data/images'), verbose_name='Зображення автомобіля')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Чи показувати на сайті?')),
                ('car_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_infos', to='app.carprice', verbose_name='Ціна оренди за автомобіль')),
            ],
            options={
                'verbose_name': 'Інформація про автомобіль',
                'verbose_name_plural': 'Інформація про автомобіль',
                'db_table': 'app_car_info',
            },
        ),
    ]
