# Generated by Django 5.0.7 on 2024-07-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_carinfo_image_alter_carprice_car_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestToCallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Запит від клієнтів на зворотній дзвінок',
                'verbose_name_plural': 'Запит від клієнтів на зворотній дзвінок',
                'db_table': 'app_request_to_call_back',
            },
        ),
    ]
