# Generated by Django 5.0.7 on 2024-07-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_requesttocallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttocallback',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Чи звязалися з клієнтом?'),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='car_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_infos', to='app.carprice', verbose_name='Клас автомобіля з цінами'),
        ),
    ]
